# coding: utf-8

# flake8: noqa

"""
    Stechs ACS NBI API v2

    Comprehensive API documentation for Stechs ACS NBI (North Bound Interface).  This API provides both synchronous and asynchronous operations for managing TR-069/CWMP devices.  ## Authentication All endpoints require HTTP Basic Authentication.  ## Async Operations Pattern Asynchronous endpoints follow this pattern: 1. Client sends request with callback URL and credentials 2. Server immediately returns a `callbackId` 3. Server processes the request in background 4. When complete, server POSTs result to the provided callback URL 5. Callback includes the `callbackId` for correlation and a `payload` with the actual result  ## Error Codes - **1015**: HTTP connection error with ACS server - **4404**: Device was not found - **4405**: Cannot execute the operation (timeout) - **4406**: ACS operation failed - **5010**: Feature not implemented yet 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stechs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "APITestApi",
    "DevicesApi",
    "FaultsApi",
    "FilesApi",
    "TasksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddObjectCallbackRequest",
    "AsyncResponse",
    "CallbackRequest",
    "DeleteDeviceTask200Response",
    "DeleteObjectCallbackRequest",
    "Device",
    "DeviceDeviceId",
    "DeviceFault",
    "DeviceTask",
    "DevicesAsyncPostRequest",
    "DevicesSerialNumberFactoryResetAsyncPostRequest",
    "DevicesSerialNumberFactoryResetAsyncPostRequestPayload",
    "DevicesSerialNumberGetParameterValueAsyncPostRequest",
    "DevicesSerialNumberRebootAsyncPostRequest",
    "DevicesSerialNumberRebootAsyncPostRequestPayload",
    "DevicesSerialNumberSetParameterValueAsyncPostRequest",
    "DownloadFileCallbackRequest",
    "DownloadFileRequest",
    "ErrorResponse",
    "ErrorResponseError",
    "FactoryResetSync200Response",
    "FaultsGetSerialNumberAsyncPostRequest",
    "FilesAllAsyncPostRequest",
    "FilesFilenameAsyncPostRequest",
    "FilesUploadAsyncPostRequest",
    "FirmwareFile",
    "FirmwareFileMetadata",
    "GetAllFirmwareFilesCallbackRequest",
    "GetDeviceListCallbackRequest",
    "GetErrorCodes200ResponseValue",
    "GetParameterValueCallbackRequest",
    "ObjectOperationRequest",
    "ParameterValue",
    "ParameterValueValue",
    "RebootSync200Response",
    "RefreshObjectCallbackRequest",
    "SetParameterValueCallbackRequest",
    "SetParameterValueRequest",
    "TR181Parameter",
    "TR181ParameterValue",
    "TasksDelTaskIdAsyncPostRequest",
    "TasksGetSerialNumberAsyncPostRequest",
    "TestWs200Response",
]

# import apis into sdk package
from openapi_client.api.api_test_api import APITestApi as APITestApi
from openapi_client.api.devices_api import DevicesApi as DevicesApi
from openapi_client.api.faults_api import FaultsApi as FaultsApi
from openapi_client.api.files_api import FilesApi as FilesApi
from openapi_client.api.tasks_api import TasksApi as TasksApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.add_object_callback_request import AddObjectCallbackRequest as AddObjectCallbackRequest
from openapi_client.models.async_response import AsyncResponse as AsyncResponse
from openapi_client.models.callback_request import CallbackRequest as CallbackRequest
from openapi_client.models.delete_device_task200_response import DeleteDeviceTask200Response as DeleteDeviceTask200Response
from openapi_client.models.delete_object_callback_request import DeleteObjectCallbackRequest as DeleteObjectCallbackRequest
from openapi_client.models.device import Device as Device
from openapi_client.models.device_device_id import DeviceDeviceId as DeviceDeviceId
from openapi_client.models.device_fault import DeviceFault as DeviceFault
from openapi_client.models.device_task import DeviceTask as DeviceTask
from openapi_client.models.devices_async_post_request import DevicesAsyncPostRequest as DevicesAsyncPostRequest
from openapi_client.models.devices_serial_number_factory_reset_async_post_request import DevicesSerialNumberFactoryResetAsyncPostRequest as DevicesSerialNumberFactoryResetAsyncPostRequest
from openapi_client.models.devices_serial_number_factory_reset_async_post_request_payload import DevicesSerialNumberFactoryResetAsyncPostRequestPayload as DevicesSerialNumberFactoryResetAsyncPostRequestPayload
from openapi_client.models.devices_serial_number_get_parameter_value_async_post_request import DevicesSerialNumberGetParameterValueAsyncPostRequest as DevicesSerialNumberGetParameterValueAsyncPostRequest
from openapi_client.models.devices_serial_number_reboot_async_post_request import DevicesSerialNumberRebootAsyncPostRequest as DevicesSerialNumberRebootAsyncPostRequest
from openapi_client.models.devices_serial_number_reboot_async_post_request_payload import DevicesSerialNumberRebootAsyncPostRequestPayload as DevicesSerialNumberRebootAsyncPostRequestPayload
from openapi_client.models.devices_serial_number_set_parameter_value_async_post_request import DevicesSerialNumberSetParameterValueAsyncPostRequest as DevicesSerialNumberSetParameterValueAsyncPostRequest
from openapi_client.models.download_file_callback_request import DownloadFileCallbackRequest as DownloadFileCallbackRequest
from openapi_client.models.download_file_request import DownloadFileRequest as DownloadFileRequest
from openapi_client.models.error_response import ErrorResponse as ErrorResponse
from openapi_client.models.error_response_error import ErrorResponseError as ErrorResponseError
from openapi_client.models.factory_reset_sync200_response import FactoryResetSync200Response as FactoryResetSync200Response
from openapi_client.models.faults_get_serial_number_async_post_request import FaultsGetSerialNumberAsyncPostRequest as FaultsGetSerialNumberAsyncPostRequest
from openapi_client.models.files_all_async_post_request import FilesAllAsyncPostRequest as FilesAllAsyncPostRequest
from openapi_client.models.files_filename_async_post_request import FilesFilenameAsyncPostRequest as FilesFilenameAsyncPostRequest
from openapi_client.models.files_upload_async_post_request import FilesUploadAsyncPostRequest as FilesUploadAsyncPostRequest
from openapi_client.models.firmware_file import FirmwareFile as FirmwareFile
from openapi_client.models.firmware_file_metadata import FirmwareFileMetadata as FirmwareFileMetadata
from openapi_client.models.get_all_firmware_files_callback_request import GetAllFirmwareFilesCallbackRequest as GetAllFirmwareFilesCallbackRequest
from openapi_client.models.get_device_list_callback_request import GetDeviceListCallbackRequest as GetDeviceListCallbackRequest
from openapi_client.models.get_error_codes200_response_value import GetErrorCodes200ResponseValue as GetErrorCodes200ResponseValue
from openapi_client.models.get_parameter_value_callback_request import GetParameterValueCallbackRequest as GetParameterValueCallbackRequest
from openapi_client.models.object_operation_request import ObjectOperationRequest as ObjectOperationRequest
from openapi_client.models.parameter_value import ParameterValue as ParameterValue
from openapi_client.models.parameter_value_value import ParameterValueValue as ParameterValueValue
from openapi_client.models.reboot_sync200_response import RebootSync200Response as RebootSync200Response
from openapi_client.models.refresh_object_callback_request import RefreshObjectCallbackRequest as RefreshObjectCallbackRequest
from openapi_client.models.set_parameter_value_callback_request import SetParameterValueCallbackRequest as SetParameterValueCallbackRequest
from openapi_client.models.set_parameter_value_request import SetParameterValueRequest as SetParameterValueRequest
from openapi_client.models.tr181_parameter import TR181Parameter as TR181Parameter
from openapi_client.models.tr181_parameter_value import TR181ParameterValue as TR181ParameterValue
from openapi_client.models.tasks_del_task_id_async_post_request import TasksDelTaskIdAsyncPostRequest as TasksDelTaskIdAsyncPostRequest
from openapi_client.models.tasks_get_serial_number_async_post_request import TasksGetSerialNumberAsyncPostRequest as TasksGetSerialNumberAsyncPostRequest
from openapi_client.models.test_ws200_response import TestWs200Response as TestWs200Response

