# coding: utf-8

"""
    Stechs ACS NBI API v2

    Comprehensive API documentation for Stechs ACS NBI (North Bound Interface).  This API provides both synchronous and asynchronous operations for managing TR-069/CWMP devices.  ## Authentication All endpoints require HTTP Basic Authentication.  ## Async Operations Pattern Asynchronous endpoints follow this pattern: 1. Client sends request with callback URL and credentials 2. Server immediately returns a `callbackId` 3. Server processes the request in background 4. When complete, server POSTs result to the provided callback URL 5. Callback includes the `callbackId` for correlation and a `payload` with the actual result  ## Error Codes - **1015**: HTTP connection error with ACS server - **4404**: Device was not found - **4405**: Cannot execute the operation (timeout) - **4406**: ACS operation failed - **5010**: Feature not implemented yet 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stechs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.devices_serial_number_factory_reset_async_post_request import DevicesSerialNumberFactoryResetAsyncPostRequest

class TestDevicesSerialNumberFactoryResetAsyncPostRequest(unittest.TestCase):
    """DevicesSerialNumberFactoryResetAsyncPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DevicesSerialNumberFactoryResetAsyncPostRequest:
        """Test DevicesSerialNumberFactoryResetAsyncPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DevicesSerialNumberFactoryResetAsyncPostRequest`
        """
        model = DevicesSerialNumberFactoryResetAsyncPostRequest()
        if include_optional:
            return DevicesSerialNumberFactoryResetAsyncPostRequest(
                callback_id = '',
                payload = openapi_client.models._devices__serial_number__factory_reset_async_post_request_payload._devices__SerialNumber__factoryReset_async_post_request_payload(
                    factory_reset = True, )
            )
        else:
            return DevicesSerialNumberFactoryResetAsyncPostRequest(
        )
        """

    def testDevicesSerialNumberFactoryResetAsyncPostRequest(self):
        """Test DevicesSerialNumberFactoryResetAsyncPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
