# coding: utf-8

"""
    Stechs ACS NBI API v2

    Comprehensive API documentation for Stechs ACS NBI (North Bound Interface).  This API provides both synchronous and asynchronous operations for managing TR-069/CWMP devices.  ## Authentication All endpoints require HTTP Basic Authentication.  ## Async Operations Pattern Asynchronous endpoints follow this pattern: 1. Client sends request with callback URL and credentials 2. Server immediately returns a `callbackId` 3. Server processes the request in background 4. When complete, server POSTs result to the provided callback URL 5. Callback includes the `callbackId` for correlation and a `payload` with the actual result  ## Error Codes - **1015**: HTTP connection error with ACS server - **4404**: Device was not found - **4405**: Cannot execute the operation (timeout) - **4406**: ACS operation failed - **5010**: Feature not implemented yet 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stechs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.files_api import FilesApi


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FilesApi()

    def tearDown(self) -> None:
        pass

    def test_download_file_async(self) -> None:
        """Test case for download_file_async

        Download file to device (asynchronous)
        """
        pass

    def test_download_file_sync(self) -> None:
        """Test case for download_file_sync

        Download file to device (synchronous)
        """
        pass

    def test_get_all_firmware_files(self) -> None:
        """Test case for get_all_firmware_files

        Get all firmware files (synchronous)
        """
        pass

    def test_get_all_firmware_files_async(self) -> None:
        """Test case for get_all_firmware_files_async

        Get all firmware files (asynchronous)
        """
        pass

    def test_get_firmware_file_detail(self) -> None:
        """Test case for get_firmware_file_detail

        Get firmware file details (synchronous)
        """
        pass

    def test_get_firmware_file_detail_async(self) -> None:
        """Test case for get_firmware_file_detail_async

        Get firmware file details (asynchronous)
        """
        pass

    def test_upload_firmware_file_async(self) -> None:
        """Test case for upload_firmware_file_async

        Upload firmware file (asynchronous)
        """
        pass

    def test_upload_firmware_file_sync(self) -> None:
        """Test case for upload_firmware_file_sync

        Upload firmware file (synchronous)
        """
        pass


if __name__ == '__main__':
    unittest.main()
