# coding: utf-8

"""
    Stechs ACS NBI API v2

    Comprehensive API documentation for Stechs ACS NBI (North Bound Interface).  This API provides both synchronous and asynchronous operations for managing TR-069/CWMP devices.  ## Authentication All endpoints require HTTP Basic Authentication.  ## Async Operations Pattern Asynchronous endpoints follow this pattern: 1. Client sends request with callback URL and credentials 2. Server immediately returns a `callbackId` 3. Server processes the request in background 4. When complete, server POSTs result to the provided callback URL 5. Callback includes the `callbackId` for correlation and a `payload` with the actual result  ## Error Codes - **1015**: HTTP connection error with ACS server - **4404**: Device was not found - **4405**: Cannot execute the operation (timeout) - **4406**: ACS operation failed - **5010**: Feature not implemented yet 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stechs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.devices_async_post_request import DevicesAsyncPostRequest

class TestDevicesAsyncPostRequest(unittest.TestCase):
    """DevicesAsyncPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DevicesAsyncPostRequest:
        """Test DevicesAsyncPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DevicesAsyncPostRequest`
        """
        model = DevicesAsyncPostRequest()
        if include_optional:
            return DevicesAsyncPostRequest(
                callback_id = '',
                payload = [
                    openapi_client.models.device.Device(
                        id = 'abcdea2332da', 
                        device_id = openapi_client.models.device_device_id.Device_deviceId(
                            serial_number = 'abcdea2332da', 
                            product_class = 'StechsDevice', 
                            manufacturer = 'Stechs', ), 
                        last_inform = '2024-01-15T10:30Z', 
                        tags = ["ManufacturerStechs"], )
                    ]
            )
        else:
            return DevicesAsyncPostRequest(
        )
        """

    def testDevicesAsyncPostRequest(self):
        """Test DevicesAsyncPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
