# coding: utf-8

"""
    Stechs ACS NBI API v2

    Comprehensive API documentation for Stechs ACS NBI (North Bound Interface).  This API provides both synchronous and asynchronous operations for managing TR-069/CWMP devices.  ## Authentication All endpoints require HTTP Basic Authentication.  ## Async Operations Pattern Asynchronous endpoints follow this pattern: 1. Client sends request with callback URL and credentials 2. Server immediately returns a `callbackId` 3. Server processes the request in background 4. When complete, server POSTs result to the provided callback URL 5. Callback includes the `callbackId` for correlation and a `payload` with the actual result  ## Error Codes - **1015**: HTTP connection error with ACS server - **4404**: Device was not found - **4405**: Cannot execute the operation (timeout) - **4406**: ACS operation failed - **5010**: Feature not implemented yet 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stechs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_delete_device_task(self) -> None:
        """Test case for delete_device_task

        Delete device task
        """
        pass

    def test_delete_device_task_async(self) -> None:
        """Test case for delete_device_task_async

        Delete device task (asynchronous)
        """
        pass

    def test_get_device_tasks(self) -> None:
        """Test case for get_device_tasks

        Get device tasks
        """
        pass

    def test_get_device_tasks_async(self) -> None:
        """Test case for get_device_tasks_async

        Get device tasks (asynchronous)
        """
        pass


if __name__ == '__main__':
    unittest.main()
