# coding: utf-8

"""
    Stechs ACS NBI API v2

    Comprehensive API documentation for Stechs ACS NBI (North Bound Interface).  This API provides both synchronous and asynchronous operations for managing TR-069/CWMP devices.  ## Authentication All endpoints require HTTP Basic Authentication.  ## Async Operations Pattern Asynchronous endpoints follow this pattern: 1. Client sends request with callback URL and credentials 2. Server immediately returns a `callbackId` 3. Server processes the request in background 4. When complete, server POSTs result to the provided callback URL 5. Callback includes the `callbackId` for correlation and a `payload` with the actual result  ## Error Codes - **1015**: HTTP connection error with ACS server - **4404**: Device was not found - **4405**: Cannot execute the operation (timeout) - **4406**: ACS operation failed - **5010**: Feature not implemented yet 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stechs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_all_firmware_files_callback_request import GetAllFirmwareFilesCallbackRequest

class TestGetAllFirmwareFilesCallbackRequest(unittest.TestCase):
    """GetAllFirmwareFilesCallbackRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAllFirmwareFilesCallbackRequest:
        """Test GetAllFirmwareFilesCallbackRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAllFirmwareFilesCallbackRequest`
        """
        model = GetAllFirmwareFilesCallbackRequest()
        if include_optional:
            return GetAllFirmwareFilesCallbackRequest(
                url = 'https://webhook.site/your-callback-url',
                username = 'callback_user',
                password = 'callback_password',
                callback_id = 'my-custom-id-123',
                limit = 50,
                offset = 0,
                sort_order = 'asc'
            )
        else:
            return GetAllFirmwareFilesCallbackRequest(
                url = 'https://webhook.site/your-callback-url',
        )
        """

    def testGetAllFirmwareFilesCallbackRequest(self):
        """Test GetAllFirmwareFilesCallbackRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
