# coding: utf-8

"""
    Stechs ACS NBI API v2

    Comprehensive API documentation for Stechs ACS NBI (North Bound Interface).  This API provides both synchronous and asynchronous operations for managing TR-069/CWMP devices.  ## Authentication All endpoints require HTTP Basic Authentication.  ## Async Operations Pattern Asynchronous endpoints follow this pattern: 1. Client sends request with callback URL and credentials 2. Server immediately returns a `callbackId` 3. Server processes the request in background 4. When complete, server POSTs result to the provided callback URL 5. Callback includes the `callbackId` for correlation and a `payload` with the actual result  ## Error Codes - **1015**: HTTP connection error with ACS server - **4404**: Device was not found - **4405**: Cannot execute the operation (timeout) - **4406**: ACS operation failed - **5010**: Feature not implemented yet 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stechs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.devices_api import DevicesApi


class TestDevicesApi(unittest.TestCase):
    """DevicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DevicesApi()

    def tearDown(self) -> None:
        pass

    def test_add_object_async(self) -> None:
        """Test case for add_object_async

        Add object (asynchronous)
        """
        pass

    def test_add_object_sync(self) -> None:
        """Test case for add_object_sync

        Add object (synchronous)
        """
        pass

    def test_delete_object_async(self) -> None:
        """Test case for delete_object_async

        Delete object (asynchronous)
        """
        pass

    def test_delete_object_sync(self) -> None:
        """Test case for delete_object_sync

        Delete object (synchronous)
        """
        pass

    def test_factory_reset_async(self) -> None:
        """Test case for factory_reset_async

        Factory reset device (asynchronous)
        """
        pass

    def test_factory_reset_sync(self) -> None:
        """Test case for factory_reset_sync

        Factory reset device (synchronous)
        """
        pass

    def test_get_parameter_value_async(self) -> None:
        """Test case for get_parameter_value_async

        Get parameter values (asynchronous)
        """
        pass

    def test_get_parameter_value_sync(self) -> None:
        """Test case for get_parameter_value_sync

        Get parameter values (synchronous)
        """
        pass

    def test_list_devices_async(self) -> None:
        """Test case for list_devices_async

        List devices (asynchronous)
        """
        pass

    def test_list_devices_sync(self) -> None:
        """Test case for list_devices_sync

        List devices (synchronous)
        """
        pass

    def test_reboot_async(self) -> None:
        """Test case for reboot_async

        Reboot device (asynchronous)
        """
        pass

    def test_reboot_sync(self) -> None:
        """Test case for reboot_sync

        Reboot device (synchronous)
        """
        pass

    def test_refresh_object_async(self) -> None:
        """Test case for refresh_object_async

        Refresh object (asynchronous)
        """
        pass

    def test_refresh_object_sync(self) -> None:
        """Test case for refresh_object_sync

        Refresh object (synchronous)
        """
        pass

    def test_set_parameter_value_async(self) -> None:
        """Test case for set_parameter_value_async

        Set parameter values (asynchronous)
        """
        pass

    def test_set_parameter_value_sync(self) -> None:
        """Test case for set_parameter_value_sync

        Set parameter values (synchronous)
        """
        pass


if __name__ == '__main__':
    unittest.main()
