# coding: utf-8

# flake8: noqa
"""
    Stechs ACS NBI API v2

    Comprehensive API documentation for Stechs ACS NBI (North Bound Interface).  This API provides both synchronous and asynchronous operations for managing TR-069/CWMP devices.  ## Authentication All endpoints require HTTP Basic Authentication.  ## Async Operations Pattern Asynchronous endpoints follow this pattern: 1. Client sends request with callback URL and credentials 2. Server immediately returns a `callbackId` 3. Server processes the request in background 4. When complete, server POSTs result to the provided callback URL 5. Callback includes the `callbackId` for correlation and a `payload` with the actual result  ## Error Codes - **1015**: HTTP connection error with ACS server - **4404**: Device was not found - **4405**: Cannot execute the operation (timeout) - **4406**: ACS operation failed - **5010**: Feature not implemented yet 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stechs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.add_object_callback_request import AddObjectCallbackRequest
from openapi_client.models.async_response import AsyncResponse
from openapi_client.models.callback_request import CallbackRequest
from openapi_client.models.delete_device_task200_response import DeleteDeviceTask200Response
from openapi_client.models.delete_object_callback_request import DeleteObjectCallbackRequest
from openapi_client.models.device import Device
from openapi_client.models.device_device_id import DeviceDeviceId
from openapi_client.models.device_fault import DeviceFault
from openapi_client.models.device_task import DeviceTask
from openapi_client.models.devices_async_post_request import DevicesAsyncPostRequest
from openapi_client.models.devices_serial_number_factory_reset_async_post_request import DevicesSerialNumberFactoryResetAsyncPostRequest
from openapi_client.models.devices_serial_number_factory_reset_async_post_request_payload import DevicesSerialNumberFactoryResetAsyncPostRequestPayload
from openapi_client.models.devices_serial_number_get_parameter_value_async_post_request import DevicesSerialNumberGetParameterValueAsyncPostRequest
from openapi_client.models.devices_serial_number_reboot_async_post_request import DevicesSerialNumberRebootAsyncPostRequest
from openapi_client.models.devices_serial_number_reboot_async_post_request_payload import DevicesSerialNumberRebootAsyncPostRequestPayload
from openapi_client.models.devices_serial_number_set_parameter_value_async_post_request import DevicesSerialNumberSetParameterValueAsyncPostRequest
from openapi_client.models.download_file_callback_request import DownloadFileCallbackRequest
from openapi_client.models.download_file_request import DownloadFileRequest
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.error_response_error import ErrorResponseError
from openapi_client.models.factory_reset_sync200_response import FactoryResetSync200Response
from openapi_client.models.faults_get_serial_number_async_post_request import FaultsGetSerialNumberAsyncPostRequest
from openapi_client.models.files_all_async_post_request import FilesAllAsyncPostRequest
from openapi_client.models.files_filename_async_post_request import FilesFilenameAsyncPostRequest
from openapi_client.models.files_upload_async_post_request import FilesUploadAsyncPostRequest
from openapi_client.models.firmware_file import FirmwareFile
from openapi_client.models.firmware_file_metadata import FirmwareFileMetadata
from openapi_client.models.get_all_firmware_files_callback_request import GetAllFirmwareFilesCallbackRequest
from openapi_client.models.get_device_list_callback_request import GetDeviceListCallbackRequest
from openapi_client.models.get_error_codes200_response_value import GetErrorCodes200ResponseValue
from openapi_client.models.get_parameter_value_callback_request import GetParameterValueCallbackRequest
from openapi_client.models.object_operation_request import ObjectOperationRequest
from openapi_client.models.parameter_value import ParameterValue
from openapi_client.models.parameter_value_value import ParameterValueValue
from openapi_client.models.reboot_sync200_response import RebootSync200Response
from openapi_client.models.refresh_object_callback_request import RefreshObjectCallbackRequest
from openapi_client.models.set_parameter_value_callback_request import SetParameterValueCallbackRequest
from openapi_client.models.set_parameter_value_request import SetParameterValueRequest
from openapi_client.models.tr181_parameter import TR181Parameter
from openapi_client.models.tr181_parameter_value import TR181ParameterValue
from openapi_client.models.tasks_del_task_id_async_post_request import TasksDelTaskIdAsyncPostRequest
from openapi_client.models.tasks_get_serial_number_async_post_request import TasksGetSerialNumberAsyncPostRequest
from openapi_client.models.test_ws200_response import TestWs200Response

