# coding: utf-8

"""
    Stechs ACS NBI API v2

    Comprehensive API documentation for Stechs ACS NBI (North Bound Interface).  This API provides both synchronous and asynchronous operations for managing TR-069/CWMP devices.  ## Authentication All endpoints require HTTP Basic Authentication.  ## Async Operations Pattern Asynchronous endpoints follow this pattern: 1. Client sends request with callback URL and credentials 2. Server immediately returns a `callbackId` 3. Server processes the request in background 4. When complete, server POSTs result to the provided callback URL 5. Callback includes the `callbackId` for correlation and a `payload` with the actual result  ## Error Codes - **1015**: HTTP connection error with ACS server - **4404**: Device was not found - **4405**: Cannot execute the operation (timeout) - **4406**: ACS operation failed - **5010**: Feature not implemented yet 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stechs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetDeviceListCallbackRequest(BaseModel):
    """
    GetDeviceListCallbackRequest
    """ # noqa: E501
    url: StrictStr = Field(description="Callback URL where results will be POSTed")
    username: Optional[StrictStr] = Field(default=None, description="Username for HTTP basic auth when calling the callback URL")
    password: Optional[StrictStr] = Field(default=None, description="Password for HTTP basic auth when calling the callback URL")
    callback_id: Optional[StrictStr] = Field(default=None, description="Optional custom callback ID (auto-generated if not provided)", alias="callbackId")
    limit: Optional[StrictInt] = None
    offset: Optional[StrictInt] = None
    serial_number: Optional[StrictStr] = Field(default=None, alias="serialNumber")
    tags: Optional[StrictStr] = None
    product_class: Optional[StrictStr] = Field(default=None, alias="productClass")
    last_inform: Optional[datetime] = Field(default=None, alias="lastInform")
    last_inform_operator: Optional[StrictStr] = Field(default='lte', alias="lastInformOperator")
    projection: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["url", "username", "password", "callbackId", "limit", "offset", "serialNumber", "tags", "productClass", "lastInform", "lastInformOperator", "projection"]

    @field_validator('last_inform_operator')
    def last_inform_operator_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['lt', 'lte', 'gt', 'gte', 'eq']):
            raise ValueError("must be one of enum values ('lt', 'lte', 'gt', 'gte', 'eq')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetDeviceListCallbackRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if username (nullable) is None
        # and model_fields_set contains the field
        if self.username is None and "username" in self.model_fields_set:
            _dict['username'] = None

        # set to None if password (nullable) is None
        # and model_fields_set contains the field
        if self.password is None and "password" in self.model_fields_set:
            _dict['password'] = None

        # set to None if callback_id (nullable) is None
        # and model_fields_set contains the field
        if self.callback_id is None and "callback_id" in self.model_fields_set:
            _dict['callbackId'] = None

        # set to None if serial_number (nullable) is None
        # and model_fields_set contains the field
        if self.serial_number is None and "serial_number" in self.model_fields_set:
            _dict['serialNumber'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if product_class (nullable) is None
        # and model_fields_set contains the field
        if self.product_class is None and "product_class" in self.model_fields_set:
            _dict['productClass'] = None

        # set to None if last_inform (nullable) is None
        # and model_fields_set contains the field
        if self.last_inform is None and "last_inform" in self.model_fields_set:
            _dict['lastInform'] = None

        # set to None if projection (nullable) is None
        # and model_fields_set contains the field
        if self.projection is None and "projection" in self.model_fields_set:
            _dict['projection'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetDeviceListCallbackRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "username": obj.get("username"),
            "password": obj.get("password"),
            "callbackId": obj.get("callbackId"),
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "serialNumber": obj.get("serialNumber"),
            "tags": obj.get("tags"),
            "productClass": obj.get("productClass"),
            "lastInform": obj.get("lastInform"),
            "lastInformOperator": obj.get("lastInformOperator") if obj.get("lastInformOperator") is not None else 'lte',
            "projection": obj.get("projection")
        })
        return _obj


