# coding: utf-8

"""
    Stechs ACS NBI API v2

    Comprehensive API documentation for Stechs ACS NBI (North Bound Interface).  This API provides both synchronous and asynchronous operations for managing TR-069/CWMP devices.  ## Authentication All endpoints require HTTP Basic Authentication.  ## Async Operations Pattern Asynchronous endpoints follow this pattern: 1. Client sends request with callback URL and credentials 2. Server immediately returns a `callbackId` 3. Server processes the request in background 4. When complete, server POSTs result to the provided callback URL 5. Callback includes the `callbackId` for correlation and a `payload` with the actual result  ## Error Codes - **1015**: HTTP connection error with ACS server - **4404**: Device was not found - **4405**: Cannot execute the operation (timeout) - **4406**: ACS operation failed - **5010**: Feature not implemented yet 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stechs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ObjectOperationRequest(BaseModel):
    """
    ObjectOperationRequest
    """ # noqa: E501
    object_name: StrictStr = Field(description="TR-069 object name", alias="objectName")
    connection_request: Optional[StrictBool] = Field(default=True, alias="connectionRequest")
    __properties: ClassVar[List[str]] = ["objectName", "connectionRequest"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ObjectOperationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ObjectOperationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "objectName": obj.get("objectName"),
            "connectionRequest": obj.get("connectionRequest") if obj.get("connectionRequest") is not None else True
        })
        return _obj


